# Generated by Django 4.0.2 on 2025-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_ticket_movie_session_alter_ticket_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('movie_session', 'row', 'seat'), name='unique_ticket_seat_per_session'),
        ),
    ]
